[build]
builder = "nixpacks"
buildCommand = "npm run build"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["nodejs_20"]

[deploy]
startCommand = "npm run start -- -p ${PORT:-3000}"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[environments.production]
